export let tourCard = [
    {
        img: "/images/tour-1.jpg",
        title: "White Boats on Body of Water",
        country: "County, Croatia",
        desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
        price: 1500,
        place: 7,
        person: 10,
        season: "summer",
        days: 5,
    },
    {
        img: "/images/tour-2.jpg",
        title: "Beautiful Diamond Beach",
        country: "Bali, Indonesia",
        desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
        price: 1200,
        place: 10,
        person: 20,
        season: "summer",
        days: 5,
    },
    {
        img: "/images/tour-3.jpg",
        title: "Viewpoint at Nangyuan island",
        country: "China",
        desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
        price: 1000,
        place: 9,
        person: 10,
        season: "summer",
        days: 7,
    },
    {
        img: "/images/tour-4.jpg",
        title: "Houses Near Ocean",
        country: "Reine, Norway",
        desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
        price: 2000,
        place: 5,
        person: 15,
        season: "summer",
        days: 7,
    },
    {
        img: "/images/tour-5.jpg",
        title: "Eiffel Tower, Paris Painting",
        country: "Paris, France",
        desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
        price: 1450,
        place: 11,
        person: 17,
        season: "summer",
        days: 7,
    },
    {
        img: "/images/tour-6.jpg",
        title: "Traveling on Man-made River",
        country: "Venice, Italy",
        desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
        price: 6000,
        place: 10,
        person: 25,
        season: "summer",
        days: 7,
    },
    {
        img: "/images/tour-7.jpg",
        title: "Picturesque View of Vernazza",
        country: "Venice, Italy",
        desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
        price: 10000,
        place: 10,
        person: 30,
        season: "summer",
        days: 5,
    },
    {
        img: "/images/tour-8.jpg",
        title: "Panoramic View of Sea Sky",
        country: "Greece",
        desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
        price: 10000,
        place: 10,
        person: 12,
        season: "summer",
        days: 7,
    },
]