export let tourCard = [
        {
            img: "/images/tour-1.jpg",
            title: "White Boats on Body of Water",
            country: "County, Croatia",
            desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
            price: 1500,
            place: 7,
            guest: 10,
            season: "summer",
        },
        {
            img: "/images/tour-2.jpg",
            title: "Beautiful Diamond Beach",
            country: "Bali, Indonesia",
            desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
            price: 1200,
            place: 10,
            guest: 20,
            season: "summer",
        },
        {
            img: "/images/tour-3.jpg",
            title: "Viewpoint at Nangyuan island",
            country: "China",
            desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
            price: 1000,
            place: 9,
            guest: 10,
        },
        {
            img: "/images/tour-4.jpg",
            title: "Houses Near Ocean",
            country: "Reine, Norway",
            desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
            price: 2000,
            place: 5,
            guest: 15,
        },
        {
            img: "/images/tour-5.jpg",
            title: "Eiffel Tower, Paris Painting",
            country: "Paris, France",
            desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
            price: 1450,
            place: 11,
            guest: 17,
        },
        {
            img: "/images/tour-6.jpg",
            title: "Traveling on Man-made River",
            country: "Venice, Italy",
            desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
            price: 6000,
            place: 10,
            guest: 25,
        },
        {
            img: "/images/tour-7.jpg",
            title: "Picturesque View of Vernazza",
            country: "Venice, Italy",
            desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
            price: 10000,
            place: 10,
            guest: 30,
        },
        {
            img: "/images/tour-8.jpg",
            title: "Panoramic View of Sea Sky",
            country: "Greece",
            desc: "Rising dramatically 200 meters above the surrounding jungle, this ancient royal",
            price: 10000,
            place: 10,
            guest: 12,
        },
    ]